---
- name: Create and configure nginx web server
  hosts: droplet
  tasks:
    - name: Install nginx server
      apt:
        name: nginx=1.18*
        state: present
    - name: Start nginx server
      service:
        name: nginx
        state: started
