---
- name: Install nodejs and npm
  hosts: droplet
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Deploy nodejs app
  hosts: droplet
  tasks:
    - name: Copy nodejs folder to a server
      copy:
        src: /Users/okryvtsov/Programming/devops/bootcamp-projects/ansible-learn/react-nodejs-example-1.0.0.tgz
        dest: /root/app-1.0.0.tgz
    - name: Unpack th nodejs tar file
      unarchive:
        src: /root/app-1.0.0.tgz
        dest: /root/
        remote_src: yes
    - name: Install dependencies
      npm:
        path: /root/package
    - name: Start the application
      command:
        chdir: /root/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
