---
- name: Install nodejs and npm
  hosts: droplet
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: droplet
  tasks:
    - name: Create linux user
      user:
        name: nigth
        comment: Night
        group: admin

- name: Deploy nodejs app
  hosts: droplet
  become: True
  become_user: night
  tasks:
    - name: Copy nodejs folder to a server
      copy:
        src: /Users/okryvtsov/Programming/devops/bootcamp-projects/ansible-learn/react-nodejs-example-1.0.0.tgz
        dest: /home/night/app-1.0.0.tgz
    - name: Unpack th nodejs tar file
      unarchive:
        src: /home/night/app-1.0.0.tgz
        dest: /home/night/
        remote_src: yes
    - name: Install dependencies
      npm:
        path: /home/night/package
    - name: Start the application
      command:
        chdir: /home/night/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
