---
- name: Install nodejs and npm
  hosts: droplet
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: droplet
  vars_files:
    - project-vars.yaml
  tasks:
    - name: Create linux user
      user:
        name: "{{linux_name}}"
        comment: Night
        group: admin
      register: user_creation_result
    - debug: msg={{user_creation_result}}

- name: Deploy nodejs app
  hosts: droplet
  vars_files:
    - project-vars.yaml
  tasks:
    - name: Unpack the nodejs tar file
      unarchive:
        src: "{{location}}/react-nodejs-example-1.0.0.tgz"
        dest: "{{destination}}"
    - name: Change directory permission
      file:
        path: "{{destination}}"
        state: directory
        owner: "{{linux_name}}"
        group: admin
        recurse: yes

- name: Install dependencies and run
  hosts: droplet
  become: True
  become_user: "{{linux_name}}"
  vars_files:
    - project-vars.yaml
  tasks:
    - name: Install dependencies
      npm:
        path: "{{destination}}/package"
    - name: Start the application
      command:
        chdir: "{{destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
